### ISSUE TITLE
"@request-target" missing parameters

### ISSUE THREAD

**Issue by tintin759** [yaronf/httpsign#1]
Hi,
It seems that "@request-target" only includes the path but not the parameters following the path.
Ex : URL is "https://localhost/myrequest?test=test"
In the signetureBase, we have: "@request-target": /myrequest
Shouldn't it be : "@request-target": /myrequest?test=test   ?
The draft section 2.2.6 specifies that "The @request-target component identifier refers to the full request  target of the HTTP request message.".
Thank you.

**Comment by yaronf** [comment]
Thanks for the bug report. Fixed in v0.1.12.
