### ISSUE TITLE
`@request-target` doesn't work with empty path

### ISSUE THREAD

**Issue by qwerty287** [yaronf/httpsign#8]
Hello,
it looks like trying to sign a request with a URL like `http://example.com` without trailing slash breaks signing/verifying. Using `http://example.com/` works as expected.
Is this intended?
Thanks for the library, everything else works fine!

**Comment by yaronf** [comment]
Hi, I'm not sure how to reproduce the issue. Can you please provide the full HTTP message you are trying to sign?

**Comment by yaronf** [comment]
Should be fixed by https://github.com/yaronf/httpsign/commit/fb1602e914ca2cd59073b653e9396d9e505d0918

Please verify.
